// This file is generated by omniidl (C++ backend) - omniORB_4_3. Do not edit.

#include "example.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

OMNI_MAYBE_UNUSED static const char* _0RL_library_version = omniORB_4_3;



Example::HelloWorld_ptr Example::HelloWorld_Helper::_nil() {
  return ::Example::HelloWorld::_nil();
}

::CORBA::Boolean Example::HelloWorld_Helper::is_nil(::Example::HelloWorld_ptr p) {
  return ::CORBA::is_nil(p);

}

void Example::HelloWorld_Helper::release(::Example::HelloWorld_ptr p) {
  ::CORBA::release(p);
}

void Example::HelloWorld_Helper::marshalObjRef(::Example::HelloWorld_ptr obj, cdrStream& s) {
  ::Example::HelloWorld::_marshalObjRef(obj, s);
}

Example::HelloWorld_ptr Example::HelloWorld_Helper::unmarshalObjRef(cdrStream& s) {
  return ::Example::HelloWorld::_unmarshalObjRef(s);
}

void Example::HelloWorld_Helper::duplicate(::Example::HelloWorld_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

Example::HelloWorld_ptr
Example::HelloWorld::_duplicate(::Example::HelloWorld_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

Example::HelloWorld_ptr
Example::HelloWorld::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


Example::HelloWorld_ptr
Example::HelloWorld::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

Example::HelloWorld_ptr
Example::HelloWorld::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_HelloWorld _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_HelloWorld* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_HelloWorld;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* Example::HelloWorld::_PD_repoId = "IDL:Example/HelloWorld:1.0";


Example::_objref_HelloWorld::~_objref_HelloWorld() {
  
}


Example::_objref_HelloWorld::_objref_HelloWorld(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::Example::HelloWorld::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
Example::_objref_HelloWorld::_ptrToObjRef(const char* id)
{
  if (id == ::Example::HelloWorld::_PD_repoId)
    return (::Example::HelloWorld_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::Example::HelloWorld::_PD_repoId))
    return (::Example::HelloWorld_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for Example::HelloWorld::sayHello

// Proxy call descriptor class. Mangled signature:
//  _cstring
class _0RL_cd_a48adf3860278656_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_a48adf3860278656_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var result;
};

void _0RL_cd_a48adf3860278656_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalString(result,0);

}

void _0RL_cd_a48adf3860278656_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalString(0);

}

const char* const _0RL_cd_a48adf3860278656_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_a48adf3860278656_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_a48adf3860278656_00000000* tcd = (_0RL_cd_a48adf3860278656_00000000*)cd;
  Example::_impl_HelloWorld* impl = (Example::_impl_HelloWorld*) svnt->_ptrToInterface(Example::HelloWorld::_PD_repoId);
  tcd->result = impl->sayHello();


}

char* Example::_objref_HelloWorld::sayHello()
{
  _0RL_cd_a48adf3860278656_00000000 _call_desc(_0RL_lcfn_a48adf3860278656_10000000, "sayHello", 9);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}

Example::_pof_HelloWorld::~_pof_HelloWorld() {}


omniObjRef*
Example::_pof_HelloWorld::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::Example::_objref_HelloWorld(ior, id);
}


::CORBA::Boolean
Example::_pof_HelloWorld::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::Example::HelloWorld::_PD_repoId))
    return 1;
  
  return 0;
}

const Example::_pof_HelloWorld _the_pof_Example_mHelloWorld;

Example::_impl_HelloWorld::~_impl_HelloWorld() {}


::CORBA::Boolean
Example::_impl_HelloWorld::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "sayHello")) {

    _0RL_cd_a48adf3860278656_00000000 _call_desc(_0RL_lcfn_a48adf3860278656_10000000, "sayHello", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
Example::_impl_HelloWorld::_ptrToInterface(const char* id)
{
  if (id == ::Example::HelloWorld::_PD_repoId)
    return (::Example::_impl_HelloWorld*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::Example::HelloWorld::_PD_repoId))
    return (::Example::_impl_HelloWorld*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
Example::_impl_HelloWorld::_mostDerivedRepoId()
{
  return ::Example::HelloWorld::_PD_repoId;
}

POA_Example::HelloWorld::~HelloWorld() {}

