package Example;


/**
* Example/HelloWorld.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from example.idl
* Monday, 20 November, 2023 9:06:27 PM IST
*/

public interface HelloWorld extends HelloWorldOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HelloWorld
