package Example;


/**
* Example/HelloWorldOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from example.idl
* Monday, 20 November, 2023 9:06:27 PM IST
*/

public interface HelloWorldOperations 
{
  String sayHello ();
} // interface HelloWorldOperations
